"""
Session Auto-Export: PDF transcript + GitHub commit
Phase 5 — Auto-Export
"""
import os
import io
import re
from datetime import datetime

# ── PDF Export (reportlab) ─────────────────────────────────────────────────────
def generate_pdf(session_data: dict) -> bytes:
    """
    Generate a formatted PDF session transcript.
    Returns raw PDF bytes.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
            Preformatted
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
    except ImportError:
        raise RuntimeError('reportlab not installed. Run: pip install reportlab')

    mode = session_data.get('mode', 'system')
    messages = session_data.get('messages', [])
    username = session_data.get('username', 'User')
    session_id = session_data.get('session_id', 'unknown')

    MODE_COLORS = {
        'developer': colors.HexColor('#00ffcc'),
        'student': colors.HexColor('#a78bfa'),
        'enquiry': colors.HexColor('#f59e0b'),
        'everyday': colors.HexColor('#fb7185'),
        'system': colors.HexColor('#6366f1'),
    }
    accent = MODE_COLORS.get(mode, colors.HexColor('#6366f1'))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'Title', parent=styles['Title'],
        fontSize=20, textColor=accent,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        'Subtitle', parent=styles['Normal'],
        fontSize=9, textColor=colors.grey,
        spaceAfter=12,
    )
    user_style = ParagraphStyle(
        'User', parent=styles['Normal'],
        fontSize=10, textColor=colors.HexColor('#1a1a2e'),
        backColor=colors.HexColor('#e8f4fd'),
        borderPadding=(6, 10, 6, 10),
        spaceAfter=6, leading=14,
        borderRadius=6,
    )
    ai_style = ParagraphStyle(
        'AI', parent=styles['Normal'],
        fontSize=10, textColor=colors.HexColor('#1a1a2e'),
        backColor=colors.HexColor('#f0fdf4'),
        borderPadding=(6, 10, 6, 10),
        spaceAfter=6, leading=14,
    )
    code_style = ParagraphStyle(
        'Code', parent=styles['Code'],
        fontSize=8, backColor=colors.HexColor('#1a1a2e'),
        textColor=colors.HexColor('#00ffcc'),
        borderPadding=(8, 10, 8, 10),
        spaceAfter=6,
        fontName='Courier',
    )

    story = [
        Paragraph(f'Nexor AI — {mode.capitalize()} Mode Session', title_style),
        Paragraph(
            f'User: {username} · Session: {session_id[:12]}... · '
            f'Exported: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}',
            subtitle_style,
        ),
        HRFlowable(width='100%', color=accent, thickness=1, spaceAfter=12),
    ]

    for msg in messages:
        role = msg.get('role', 'user')
        content = msg.get('content', '')

        if role == 'user':
            story.append(Paragraph(f'<b>You:</b> {content}', user_style))
        else:
            # Extract code blocks separately
            parts = re.split(r'(```(?:\w+)?\n[\s\S]*?```)', content)
            for part in parts:
                if part.startswith('```'):
                    code = re.sub(r'```(?:\w+)?\n?', '', part).strip()
                    story.append(Preformatted(code, code_style))
                elif part.strip():
                    clean = part.replace('<', '&lt;').replace('>', '&gt;')
                    story.append(Paragraph(f'<b>Nexor AI:</b> {clean}', ai_style))

        story.append(Spacer(1, 4))

    story.append(HRFlowable(width='100%', color=colors.grey, thickness=0.5, spaceBefore=12))
    story.append(Paragraph('Generated by Nexor AI — nexor.ai', subtitle_style))

    doc.build(story)
    return buf.getvalue()


# ── GitHub Export ──────────────────────────────────────────────────────────────
def commit_to_github(
    session_data: dict,
    github_pat: str,
    repo_name: str,
) -> dict:
    """
    Commit extracted code snippets to a GitHub repository.
    Returns {'url': commit_url} or {'error': ...}
    """
    try:
        from github import Github, GithubException
    except ImportError:
        return {'error': 'PyGithub not installed. Run: pip install PyGithub'}

    messages = session_data.get('messages', [])
    mode = session_data.get('mode', 'system')
    session_id = session_data.get('session_id', 'unknown')[:8]
    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')

    # Extract all code blocks from AI messages
    snippets = []
    for msg in messages:
        if msg.get('role') in ('model', 'assistant', 'ai'):
            blocks = re.findall(r'```(\w+)?\n([\s\S]*?)```', msg.get('content', ''))
            for lang, code in blocks:
                snippets.append({'lang': lang or 'txt', 'code': code.strip()})

    if not snippets:
        return {'error': 'No code blocks found in this session.'}

    try:
        g = Github(github_pat)
        repo = g.get_repo(repo_name)
        branch = repo.default_branch
        commit_files = {}

        for i, snippet in enumerate(snippets[:10]):  # Max 10 files per commit
            ext = snippet['lang'] if snippet['lang'] != 'txt' else 'txt'
            filename = f'nexor-exports/{mode}/{session_id}/snippet_{i + 1}.{ext}'
            commit_files[filename] = snippet['code']

        # Create tree + commit
        head_sha = repo.get_branch(branch).commit.sha
        base_tree = repo.get_git_tree(head_sha)

        new_tree = repo.create_git_tree(
            [
                {'path': path, 'mode': '100644', 'type': 'blob',
                 'content': content}
                for path, content in commit_files.items()
            ],
            base_tree=base_tree,
        )

        parent_commit = repo.get_git_commit(head_sha)
        new_commit = repo.create_git_commit(
            message=f'[Nexor AI] {mode} session export — {timestamp}',
            tree=new_tree,
            parents=[parent_commit],
        )
        repo.get_git_ref(f'heads/{branch}').edit(new_commit.sha)

        return {
            'url': f'https://github.com/{repo_name}/commit/{new_commit.sha}',
            'files_committed': len(commit_files),
            'snippet_count': len(snippets),
        }

    except GithubException as e:
        return {'error': f'GitHub error: {e.data.get("message", str(e))}'}
    except Exception as e:
        return {'error': str(e)}
